package sharefile;

import static java.lang.Thread.sleep;
import sharefile.jdbc;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author seema
 */
public class hist extends javax.swing.JFrame {

    /**
     * Creates new form hist
     */
    static Connection con;
    static Statement stmt;
    static DefaultTableModel t,t1;
    FirstPage fp;
    
    public hist() {
        initComponents();
       // String []args={};
       // this.main(args);
    }
    public hist(FirstPage ob) {
        initComponents();
       // String []args={};
       // this.main(args);
       fp=ob;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        recTable = new javax.swing.JTable();
        rbackButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sentTable = new javax.swing.JTable();
        sbackButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        recTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sender", "File name", "Format", "Time", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(recTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 429;
        gridBagConstraints.ipady = 79;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(58, 58, 0, 123);
        jPanel3.add(jScrollPane2, gridBagConstraints);

        rbackButton.setText("Back");
        rbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 246, 219, 0);
        jPanel3.add(rbackButton, gridBagConstraints);

        jTabbedPane1.addTab("RECIEVED FILES", jPanel3);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        sentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Reciever", "Name", "Format", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(sentTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 429;
        gridBagConstraints.ipady = 89;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(42, 62, 0, 119);
        jPanel1.add(jScrollPane3, gridBagConstraints);

        sbackButton.setText("Back");
        sbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 248, 221, 0);
        jPanel1.add(sbackButton, gridBagConstraints);

        jTabbedPane1.addTab("SENT FILES", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbackButtonActionPerformed
        // TODO add your handling code here:
        fp.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_sbackButtonActionPerformed

    private void rbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbackButtonActionPerformed
        // TODO add your handling code here:
        fp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rbackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new hist().setVisible(true);
                /* t=(DefaultTableModel)sentTable.getModel();
        t.setRowCount(0);
        t1=(DefaultTableModel)recTable.getModel();
        t1.setRowCount(0);*/
            }
        });
        
        
        // DefaultTableModel st,rt;
        //st = (DefaultTableModel)sendtable.getModel();
        //st.setRowCount(0);
        //rt=(DefaultTableModel)rectable.getModel();
        //rt.setRowCount(0);
        
        jdbc j=new jdbc();
        try
        {
         
            String sql="SELECT `rec_name` , `name` , `type` , `date`\n" +
                "FROM `send` , `fileinfo`\n" +
                "WHERE id = fileid";
            ResultSet[] rs=new ResultSet[50];
            j.search(sql, rs);
                int count=0;
                
            t=(DefaultTableModel)sentTable.getModel();
        t.setRowCount(0);
       t1=(DefaultTableModel)recTable.getModel();
        t1.setRowCount(0);
            while(rs[0].next())
            {
                String rec=rs[0].getString("rec_name");
                String name=rs[0].getString("name");
                String type=rs[0].getString("type");
                String time=rs[0].getString("date");
                
                System.out.println(rec+name+type+time);
                t.addRow(new String[]{});
                sentTable.getModel().setValueAt(rec, count, 0);
                sentTable.getModel().setValueAt(name, count, 1);
                sentTable.getModel().setValueAt(type, count, 2);
                sentTable.getModel().setValueAt(time, count, 3);
                count++;
                
                
                
            }
            
             sql="SELECT `send_name` , `name` , `type` , `date`,`location`\n" +
                "FROM `receive` , `fileinfo`\n" +
                "WHERE id = fileid";
            ResultSet[] rs1=new ResultSet[50];
            j.search(sql, rs1);
                count=0;
            while(rs1[0].next())
            {
                t1.addRow(new String[]{});
                String send=rs1[0].getString("send_name");
                String name=rs1[0].getString("name");
                String type=rs1[0].getString("type");
                String time=rs1[0].getString("date");
                String location=rs1[0].getString("location");
                
                System.out.println(send+name+type+time+location);
                recTable.getModel().setValueAt(send, count, 0);
                recTable.getModel().setValueAt(name, count, 1);
                recTable.getModel().setValueAt(type, count, 2);
                recTable.getModel().setValueAt(time, count, 3);
                recTable.getModel().setValueAt(location, count, 4);
                count++;
            }
            
       
        
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton rbackButton;
    public static javax.swing.JTable recTable;
    private javax.swing.JButton sbackButton;
    private static javax.swing.JTable sentTable;
    // End of variables declaration//GEN-END:variables
}
